---
AWSTemplateFormatVersion: '2010-09-09'
Description: Sample template
Resources:
  RootRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 'iam:PassRole'
                Resource: 'arn:aws:iam::111122223333:role/EC2-roles-for-XYZ-*'
  RootInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - !Ref RootRole
  expectations:
    rules:
      IAM_ROLE_NO_WILDCARD_RESOURCE_ON_PASSROLE: PASS
  SampleVolume:
    Type: AWS::EC2::Volume
    Properties:
      Encrypted: true
      Size: 10
      VolumeType: gp2
  FooRole:
    Type: 'AWS::IAM::Role'
    Properties:
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 
                  - 'iam:PassRole'
                  - 's3:ListBuckets'
                Resource: '*'
  TestPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: root
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: 
            - 'iam:PassRole'
            - 's3:ListBuckets'
            Resource: '*'
      Roles:
        - !Ref RootRole
