name: Continuous Integration

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  testRules:
    # cfn-guard binary for macos
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run guard rules tests
      shell: bash
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/aws-cloudformation/cloudformation-guard/main/install-guard.sh | sh
        cfn-guard test -d ./rules/
    ## If test fails run step to pull out only failed tests
    - name: Display Failed Rules Only
      if: ${{ failure() }}
      shell: bash
      run: |
        cfn-guard test -d ./rules/ | grep "FAIL Rules:" -B 2 -A 1

# jobs:
#   testRules:
#     # cfn-guard binary for macos
#     runs-on: macos-latest
#     steps:
#     - uses: actions/checkout@v2
#     - name: Run guard rules tests
#       shell: bash
#       run: |
#         bin/cfn-guard test -d ./rules/
#     ## If test fails run step to pull out only failed tests
#     - name: Display Failed Rules Only
#       if: ${{ failure() }}
#       shell: bash
#       run: |
#         bin/cfn-guard test -d ./rules/ | grep "FAIL Rules:" -B 2 -A 1