name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  testRules:
    if: github.ref == 'refs/heads/master'
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - name: "Setup - Checkout"
        uses: actions/checkout@v2.1.0
      - name: "Validate Guard Registry Rules"
        shell: bash
        run: bin/cfn-guard test -d ./rules/aws/  | grep "FAIL Rules:" -B 2 -A 1
