name: Continuous Integration

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  testRules:
    # cfn-guard binary for macos
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run guard rules tests
      shell: bash
      run: |
        bin/cfn-guard test -d ./rules/
    ## If test fails run step to pull out only failed tests
    - name: Display Failed Rules Only
      if: ${{ failure() }}
      shell: bash
      run: |
        bin/cfn-guard test -d ./rules/ | grep "FAIL Rules:" -B 2 -A 1